#!/usr/bin/env python3
"""Generate source-level differential fixtures. No upstream implementation is vendored.
Supply the unmodified liblwgeom/lwalgorithm.c from the documented PostGIS snapshot.
Only stdlib + system C compiler are needed; upstream code is compiled in a temp directory.
"""
import argparse
import ctypes
import hashlib
import random
import subprocess
import tempfile
from pathlib import Path

SNAPSHOT = '33904db915bb3c2ff0f23a69f047bfdb5b93fcc0'
SOURCE_SHA256 = 'a4d4d07bb9275bf904e80652e44b8f74e3102dbd9fc0ef30d0ad876776b1c810'
SEED = 20261007


def extract(source, name):
    start = source.index(name + '(')
    end = source.index('{', start)
    depth = 1
    end += 1
    while depth:
        depth += (source[end] == '{') - (source[end] == '}')
        end += 1
    return source[start:end]


def generate(source_path, output):
    if hashlib.sha256(source_path.read_bytes()).hexdigest() != SOURCE_SHA256:
        raise ValueError("Source digest does not match the documented PostGIS snapshot")
    source = source_path.read_text()
    stub = '''#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdarg.h>
typedef struct {int size; char data[];} lwvarlena_t;
typedef struct {double xmin,ymin,xmax,ymax;} GBOX;
#define LWVARHDRSZ 4
#define LWSIZE_SET(a,b) ((a)=(b))
#define lwalloc malloc
#define GEOHASH_MAX_DOUBLE_PRECISION_CHARS 20
static char *base32="0123456789bcdefghjkmnpqrstuvwxyz";
static void lwerror(const char *fmt, ...) { exit(2); }
'''
    code = stub + '\nlwvarlena_t *\n' + extract(source, 'geohash_point')
    code += '\nvoid\n' + extract(source, 'decode_geohash_bbox')
    code += '\nint\n' + extract(source, 'lwgeom_geohash_precision')
    code += '''
void reference_encode(double x,double y,int p,char *out) {
 lwvarlena_t *v=geohash_point(x,y,p); memcpy(out,v->data,p); out[p]=0; free(v);
}
int reference_precision(double x0,double y0,double x1,double y1) {
 GBOX b={x0,y0,x1,y1}, bounds={0}; return lwgeom_geohash_precision(b,&bounds);
}
'''
    with tempfile.TemporaryDirectory(prefix='pintail-postgis-') as tmp:
        cfile = Path(tmp) / 'reference.c'
        libfile = Path(tmp) / 'reference.so'
        cfile.write_text(code)
        subprocess.run(['cc', '-shared', '-fPIC', '-O0', str(cfile), '-o', str(libfile)], check=True)
        lib = ctypes.CDLL(str(libfile))
        lib.reference_encode.argtypes = [ctypes.c_double, ctypes.c_double, ctypes.c_int, ctypes.c_char_p]
        lib.reference_precision.argtypes = [ctypes.c_double] * 4
        lib.reference_precision.restype = ctypes.c_int
        lib.decode_geohash_bbox.argtypes = [ctypes.c_char_p, ctypes.POINTER(ctypes.c_double), ctypes.POINTER(ctypes.c_double), ctypes.c_int]
        def encode(x, y, p):
            buf = ctypes.create_string_buffer(p + 1)
            lib.reference_encode(x, y, p, buf)
            return buf.value.decode()
        rng = random.Random(SEED)
        statements = [f'''# Upstream PostGIS {SNAPSHOT}
# liblwgeom/lwalgorithm.c SHA256 {hashlib.sha256(source_path.read_bytes()).hexdigest()}
# Deterministic source-level differential vectors, seed {SEED}.
# Generated by scripts/generate_postgis_geohash_vectors.py; no PostgreSQL server assumed.
require pintail
''']
        def q(sql, expected):
            statements.append(f'query I\n{sql}\n----\n{expected}\n')
        points = [(-126.,48.), (0.,0.), (-180.,-90.), (180.,90.), (0.,90.), (0.,-90.), (-180.,0.), (180.,0.)]
        points += [(rng.uniform(-180,180), rng.uniform(-90,90)) for _ in range(64)]
        for x, y in points:
            for p in [1, 5, 12, 20]:
                h = encode(x,y,p)
                q(f"SELECT st_geohash('POINT({x!r} {y!r})'::GEOMETRY, {p}) = '{h}' AND st_geohash({y!r}, {x!r}, {p}) = '{h}';", 'true')
        for _ in range(64):
            x,y = rng.uniform(-170,170),rng.uniform(-80,80)
            w,h = 10**rng.uniform(-6,0),10**rng.uniform(-6,0)
            x1,y1=x+w,y+h
            p=lib.reference_precision(x,y,x1,y1)
            code=encode(x+(x1-x)/2,y+(y1-y)/2,p)
            q(f"SELECT st_geohash('LINESTRING({x!r} {y!r}, {x1!r} {y1!r})'::GEOMETRY) = '{code}';", 'true')
        hashes = ['', 'c0w3h', '9qqj7nmxncgyy4d0dbxqz0', 'ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ']
        hashes += [''.join(rng.choice('0123456789bcdefghjkmnpqrstuvwxyz') for _ in range(rng.randint(1,40))) for _ in range(40)]
        for h in hashes:
            for p in [-1,0,4,100]:
                lat,lon = (ctypes.c_double*2)(),(ctypes.c_double*2)()
                lib.decode_geohash_bbox(h.encode(),lat,lon,p)
                q(f"SELECT st_geohash_bbox('{h}', {p}) = {{'min_lat': {lat[0]!r}, 'min_lon': {lon[0]!r}, 'max_lat': {lat[1]!r}, 'max_lon': {lon[1]!r}}};", 'true')
                x,y = lon[0]+(lon[1]-lon[0])/2,lat[0]+(lat[1]-lat[0])/2
                q(f"SELECT st_aswkb(st_pointfromgeohash('{h}', {p})) = st_aswkb('POINT({x!r} {y!r})'::GEOMETRY);", 'true')
                ring = ','.join(f'{a!r} {b!r}' for a,b in [(lon[0],lat[0]),(lon[0],lat[1]),(lon[1],lat[1]),(lon[1],lat[0]),(lon[0],lat[0])])
                q(f"SELECT st_aswkb(st_geomfromgeohash('{h}', {p})) = st_aswkb('POLYGON(({ring}))'::GEOMETRY);", 'true')
        output.write_text('\n'.join(statements))
        print(f'Wrote {len(statements)-1} source-derived vectors to {output}')


if __name__ == '__main__':
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--source', required=True, type=Path)
    parser.add_argument('--output', type=Path, default=Path('test/sql/geohash_postgis_vectors.test'))
    args=parser.parse_args()
    generate(args.source,args.output)
